amfm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # include url config from each app's urls
    path('', include('status.urls')),
    path('biodata/', include('biodata.urls')),
    path('example/', include('example.urls')),
]

biodata/urls.py
from django.urls import path
from . import views

app_name = 'biodata'

urlpatterns = [
    path('', views.biodata_page, name='biodata_page'),
]

example/urls.py
from django.urls import path
from . import views

app_name = 'example'

urlpatterns = [
    path('', views.example_page, name='index'),
]

status/urls.py
from django.urls import path
from . import views

app_name = 'status'

urlpatterns = [
    path('', views.status_page, name='status_page'),
]

biodata/models.py
from django.db import models

# Create your models here.

# Create your models here.
class Biodata(models.Model):
    full_name = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    age = models.PositiveSmallIntegerField()
    birthday = models.DateField(auto_now=False, auto_now_add=False)
    address = models.CharField(max_length=255)
    education = models.CharField(max_length=255)
    hobby = models.CharField(max_length=255)
    favorite_food = models.CharField(max_length=255)
    favorite_subject = models.CharField(max_length=255)
    number_of_siblings = models.PositiveSmallIntegerField()

example/models.py
from django.db import models

# Create your models here.

status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    # TODO: add models field for name & status
    # reference for models fields: https://docs.djangoproject.com/en/3.1/topics/forms/#more-on-fields
    name = models.CharField(max_length=55)
    status = models.TextField()

biodata/forms.py
from django import forms

from .models import Biodata

class BiodataForm(forms.ModelForm):
    class Meta:
        model = Biodata
        fields = "__all__"
        widgets = {
            'birthday': forms.DateInput(
                attrs={'type' : 'date'}
            ),
        }

example/forms.py
from django import forms
from django.forms.widgets import CheckboxSelectMultiple

FAVORITE_SUBJECT_CHOICES = [
    ('MPKTB', 'MPKT B'),
    ('DDP1', 'DDP 1'),
    ('MATDAS', 'MATDAS'),
    ('FISDAS', 'FISDAS'),
    ('PSD', 'PSD'),
    ('PPW', 'PPW'),
    ('ALIN', 'ALIN'),
]

class FavSubject(forms.Form):
    favorite_subject = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=FAVORITE_SUBJECT_CHOICES,
    )

status/forms.py
from django import forms

class StatusForm(forms.Form):
    # TODO: add forms instance in adjacent to models' attribute
    # reference for forms fields: https://docs.djangoproject.com/en/3.1/topics/forms/#more-on-fields
    name = forms.CharField(max_length=55)
    status = forms.CharField(widget=forms.Textarea)

biodata/views.py
# Create your views here.
from django.shortcuts import render, redirect

# Import forms & models
from .forms import BiodataForm
from .models import Biodata

# Create your views here.
def biodata_page(request):
    context = {}

    if request.method == 'POST':
        form = BiodataForm(request.POST)
        if form.is_valid():
            form.save() # versi 1
            # models.Biodata(**form.cleaned_data).save() # versi 2
            return redirect('biodata:biodata_page')
    else:
        form = BiodataForm()

    context['form'] = form
    context['biodatas'] = Biodata.objects.all()

    return render(request, 'biodata/biodata.html', context)

example/views.py
from django.shortcuts import render

# import form yang ingin ditampilkan dari forms.py
from .forms import FavSubject

# Create your views here.
def example_page(request):

    # instantiate objek dictionary
    # untuk menyimpan konteks yg akan di-pass ke template
    context = {}

    # mem-pass forms ke template
    # menambahkan isi objek dictionary dgn key = from dan value = FavSubject
    context["form"] = FavSubject

    return render(request, 'example/example.html', context)

status/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Import forms & models
from .forms import StatusForm
from .models import Status

# Create your views here.
def status_page(request):

    # TODO: Implement views for status application
    # the views must consist of two (2) agendas
    # 1. pass form and statuses to template
    # 2. handle status submit request from template
    context = {}

    if request.method == 'POST':
         form = StatusForm(request.POST)
         if form.is_valid():
             # Parse the required data from form
             # Note that you need to use "cleaned_data" in order to get cleaned data (duh)
             # To tell the differences between clean and raw form data,
             # you can do print(form) and print(form.cleaned_data)
             name = form.cleaned_data['name']
             status = form.cleaned_data['status']

             # Save the newly-posted status on our database/models
             # You can save it by creating new models object
             Status.objects.create(name=name, status=status)
             print(Status.objects.get(status=status))

             return HttpResponseRedirect('/')

         else:
            form = StatusForm()

         context["form"] = form
         context["statuses"] = Status.objects.all()

         return render(request, 'status/status.html', context)

biodata/templates/biodata.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>Biodata</h1>

        <form action="{% url 'biodata:biodata_page' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <input type="submit" value="Submit!">
        </form>

        {% for biodata in biodatas %}
            <h5>{{ 'full_name'|title }}: {{ biodata.full_name }}</h5>
            <p>{{ 'name'|title }}: {{ biodata.name }}</p>
            <p>{{ 'age'|title }}: {{ biodata.age }}</p>
            <p>{{ 'birthday'|title }}: {{ biodata.birthday }}</p>
            <p>{{ 'address'|title }}: {{ biodata.address }}</p>
            <p>{{ 'education'|title }}: {{ biodata.education }}</p>
            <p>{{ 'hobby'|title }}: {{ biodata.hobby }}</p>
            <p>{{ 'favorite_food'|title }}: {{ biodata.favorite_food }}</p>
            <p>{{ 'favorite_subject'|title }}: {{ biodata.favorite_subject }}</p>
            <p>{{ 'number_of_siblings'|title }}: {{ biodata.number_of_siblings }}</p>
        {% endfor %}
    </div>
</body>
</html>

example/templates/example/example.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Example</title>

    <!-- Import stylesheet pakai jinja -->
    <link rel="stylesheet" href="{% static 'example/example.css' %}">
</head>
<body>
    <div>
        <h1>Using regular HTML approach</h1>

        <!-- Using regular HTML approach -->
        <p>Favorite Subject:</p>

        <form action="#" method="post">
            <input type="checkbox" id="subject1" name="subject1" value="MPKTB">
            <label for="subject1">MPKT B</label><br>
            <input type="checkbox" id="subject2" name="subject2" value="DDP1">
            <label for="subject2">DDP 1</label><br>
            <input type="checkbox" id="subject3" name="subject3" value="MATDAS">
            <label for="subject3">MATDAS</label><br>
            <input type="checkbox" id="subject4" name="subject4" value="FISDAS">
            <label for="subject4">FISDAS</label><br>
            <input type="checkbox" id="subject5" name="subject5" value="PSD">
            <label for="subject5">PSD</label><br>
            <input type="checkbox" id="subject6" name="subject6" value="ALIN">
            <label for="subject6">ALIN</label><br>
            <input type="checkbox" id="subject7" name="subject7" value="PPW">
            <label for="subject7">PPW</label><br>


            <input type="submit" disabled="disabled">
        </form>
    </div>

    <div>
        <h1>Using Django built in form API</h1>

        <!-- Using Django built in form API -->
        <form action="#" method="post">
            {% csrf_token %}
            {{ form }}

            <input type="submit" disabled="disabled">
        </form>
    </div>

    <div>
        <h1>For another example, please visit the following links</h1>

    </div>
</body>
</html>

status/templates/status/status.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Import stylesheet pakai jinja -->
    <link rel="stylesheet" href="{% static 'status/status.css' %}">
</head>
<body>

    <div>

        <!-- TODO: Render form django -->
        <form action="{% url 'status:status_page' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <input type="submit" value="Post!">
        </form>

        <!-- TODO: Render semua status yang udah diposting -->
        {% for status in statuses %}
            <h5>{{status.name}}</h5>
            <p>{{status.status}}</p>
        {% endfor %}

    </div>

</body>
</html>